server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tu_db
    username: tu_usuario
    password: tu_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  openai:
    api:
      key: ${OPENAI_API_KEY}
      url: https://api.openai.com/v1/chat/completions
      model: gpt-5-mini
